Migrate the script to use per-customer-id endpoint and auth by default
observeinc/linux-host-configuration-scripts pull request #17
Opened 2022-08-09 18:54 UTC by chenjiayuan

2022-08-09 18:54 UTC, chenjiayuan commented
DO NOT MERGE YET

2022-08-11 16:02 UTC, arthur-observe requested changes
Need to checkin with @jlebaugh and @mwiser-1 to see how this affects apps

2022-08-11 23:46 UTC, chenjiayuan commented on README.md
> +- Optional --observe_host_name - Defaults to https://<YOUR_OBSERVE_CUSTOMERID>collect.observe.com/
Fixed.

2022-08-12 15:59 UTC, mwiser-1 reviewed
Works for me - no issues for host monitoring or linux host

2022-08-12 20:04 UTC, jlebaugh approved these changes

2022-08-26 21:15 UTC, merged